spring.application.name=CampusCanteenBackend

spring.main.banner-mode=off

spring.datasource.url=jdbc:mysql://localhost:3306/campuscanteen
spring.datasource.username=root
spring.datasource.password=lachu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true